adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_isroot: false
adx_name: Product Details
adx_pagetemplateid: 48155ce8-9d71-4c78-ad37-cb26f007cd7a
adx_parentpageid: f499a8f8-8635-44f9-9819-0eedb3457051
adx_partialurl: product-details
adx_publishingstateid: ae213bd3-2897-4dab-83f0-a65e9c32b194
adx_rootwebpageid: 1564c096-7814-484d-b396-5a7aa99fcb60
adx_sharedpageconfiguration: false
adx_webpageid: 46bd6eee-f609-4657-a1b0-b0214364d122
adx_webpagelanguageid: eb21ffdf-635b-416c-a2bc-14a8f1bc6c0e
